services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py